name: fetchnow
description: "An API platform for building and using APIs"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  path_provider: ^2.1.5
  intl: ^0.20.2
  equatable: ^2.0.7
  window_manager: ^0.4.3
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.3.3
  flutter_gen_runner: 5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/manrope/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/manrope/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/manrope/Manrope-Bold.ttf
          weight: 700

flutter_gen:
  assets:
    enabled: true
    outputs:
      class_name: Assets
      package_parameter_enabled: false
  output: lib/src/core/generated
  line_length: 80

  integrations:
    flutter_svg: true
